# Changes here will be overwritten by Copier
AddCopierCI: true
AnswerStrategy: recommended-ask
Authors: Benedikt Ehinger <thesisart@benediktehinger.de>
CheckExplicitImports: false
CodeOfConductContact: thesisart@benediktehinger.de
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Benedikt Ehinger
MarkdownIndentation: 2
PackageName: ThesisArt
PackageOwner: s-ccs
PackageUUID: 220af752-98c4-58c6-85e7-d9433743e73d
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
